async function downloadPDF() {
  const { jsPDF } = window.jspdf;
  const logo = "images/logo-removebg-preview.png";

  // Create a new PDF document
  const doc = new jsPDF();

  const img = new Image();
  img.src = logo;
  await new Promise((resolve) => (img.onload = resolve));
  doc.addImage(img, "PNG", 15, 10, 18, 18);

  // Set font and colors
  doc.setFont("Helvetica", "ExtraBold");
  doc.setFontSize(20);
  doc.setTextColor("#88531E");
  doc.text("SWEET AVENUE", 35, 20);
  doc.setFontSize(16);
  doc.text("COFFEE • BAKESHOP", 35, 25);

  // User information
  doc.setFontSize(18);
  doc.setFont("Helvetica", "bold");
  const today = new Date();
  const reportDateTime = `Reports For (${today.toLocaleString()})`;
  const textWidth =
    (doc.getStringUnitWidth(reportDateTime) * doc.internal.getFontSize()) /
    doc.internal.scaleFactor;
  const center = (doc.internal.pageSize.width - textWidth) / 2;
  doc.text(reportDateTime, center, 40);

  // Sales and order details
  doc.setFontSize(12);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor("#000000");

  doc.text("Generated by: ", 15, 50);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor("#88531E");
  doc.text(user, 80, 50);

  doc.setFont("Helvetica", "normal");
  doc.setTextColor("#000000");
  doc.text("Sales Today:", 15, 60);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor("#88531E");
  doc.text(`${todaySale}`, 80, 60);

  doc.setFont("Helvetica", "normal");
  doc.setTextColor("#000000");
  doc.text("Orders Today:", 15, 70);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor("#88531E");
  doc.text(orderToday.toString(), 80, 70);

  doc.setFont("Helvetica", "normal");
  doc.setTextColor("#000000");
  doc.text("Weekly Sales:", 15, 80);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor("#88531E");
  doc.text(`${weeklySale}`, 80, 80);
  doc.setFont("Helvetica", "semibold");
  doc.text(`(${weekDuration})`, 15, 85);

  doc.setFont("Helvetica", "normal");
  doc.setTextColor("#000000");
  doc.text("Monthly Sales:", 15, 90);
  doc.setFont("Helvetica", "bold");
  doc.setTextColor("#88531E");
  doc.text(`${monthlySale}`, 80, 90);
  doc.setFont("Helvetica", "semibold");
  doc.text(`(${dateRange})`, 15, 95);

  // Weekly Sales Table
  doc.setFontSize(14);
  doc.setFont("Helvetica", "bold");
  doc.text("Weekly Sales", 15, 105);

  // Parse the JSON data fetched from PHP
  const weeklySalesHeaders = ["Date", "Sales"];
  const weeklySalesDataFormatted = weeklySalesData.map((entry) => [
    entry.date,
    `${parseFloat(entry.total_sales).toFixed(2)}`,
  ]);

  // Weekly Sales Table Styling
  doc.autoTable({
    startY: 110,
    head: [weeklySalesHeaders],
    body: weeklySalesDataFormatted,
    theme: "grid",
    styles: {
      textColor: "#88531E",
      fillColor: "#88531E",
      halign: "center",
    },
    headStyles: {
      fillColor: "#88531E",
      textColor: "#ffffff",
    },
    bodyStyles: {
      fillColor: "#ffffff",
      textColor: "#88531E",
    },
  });

  // Predicted Weekly Sales Table
  doc.setFontSize(14);
  doc.setFont("Helvetica", "bold");
  doc.text("Predicted Weekly Sales", 15, doc.previousAutoTable.finalY + 10);

  // Fetching and using predicted sales data
  const predictedSalesData = {
    predictions: [
      { date: "2024-06-01", sales_prediction: 4051.77 },
      { date: "2024-06-02", sales_prediction: 4299.14 },
      { date: "2024-06-03", sales_prediction: 4546.51 },
      { date: "2024-06-04", sales_prediction: 4793.89 },
      { date: "2024-06-05", sales_prediction: 5041.26 },
      { date: "2024-06-06", sales_prediction: 5288.63 },
    ],
    sales_sum: 28021.2,
  };

  const predictedWeeklySalesHeaders = ["Date", "Sales"];
  const predictedWeeklySalesData = predictedSalesData.predictions.map(
    (prediction) => [
      prediction.date,
      `${prediction.sales_prediction.toFixed(2)}`,
    ]
  );

  // Predicted Weekly Sales Table Styling
  doc.autoTable({
    startY: doc.previousAutoTable.finalY + 15,
    head: [predictedWeeklySalesHeaders],
    body: predictedWeeklySalesData,
    theme: "grid",
    styles: {
      textColor: "#88531E",
      fillColor: "#88531E",
      halign: "center",
    },
    headStyles: {
      fillColor: "#88531E",
      textColor: "#ffffff",
    },
    bodyStyles: {
      fillColor: "#ffffff",
      textColor: "#88531E",
    },
  });

  // Top Pick and Popular Combo Table
  doc.setFontSize(14);
  doc.setFont("Helvetica", "bold");
  doc.text("Weekly Top Sold Products", 15, doc.previousAutoTable.finalY + 10);

  const topPickHeaders = ["Top Pick", "", "Popular Combo"];
  doc.autoTable({
    startY: doc.previousAutoTable.finalY + 15,
    head: [topPickHeaders],
    body: topPickData,
    theme: "grid",
    styles: {
      textColor: "#88531E",
      fillColor: "#ffffff",
      halign: "center",
    },
    headStyles: {
      fillColor: "#ffffff",
      textColor: "#88531E",
    },
    bodyStyles: {
      fillColor: "#ffffff",
      textColor: "#88531E",
    },
  });

  doc.save("report.pdf");
}
